### ISSUE TITLE
Is there any way to get list of all Satz present in a file by their id

### ISSUE THREAD

**Issue by saps31** [oboehm/gdv.xport#76]
Currently, we are able to get the sender of the file like this -
`Satz satz = SatzFactory.getSatz(SatzTyp.of("0001"));`

It is possible that the file has multiple senders. How can we get all the senders(0001) present in the file?

**Comment by saps31** [comment]
Hi @oboehm , 
Any update on this? I need to fetch all the senders present in the file, would that be possible ?

**Comment by oboehm** [comment]
Sorry for the late answer but since some weeks I did not receive any mail from github. But now to your question. With
`Satz satz = SatzFactory.getSatz(SatzTyp.of("0001"));`
you get an empty "Vorsatz". There is only one field "Absender" and one field "Adressat".

Do you want to export or to import records? Since you a file with the data I guess you want to import it. In this case have a look at ImportExport class in the gdv.xport.demo Package how to import several instances of "Datenpaket". In each Datenpaket you find a Satz 0001 (Vorsatz) with sender.

Another approach: use the DatenpaketStreamer if you are only interested in some Satzarten

**Comment by saps31** [comment]
Alright, thanks for the info
